//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace encuestas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_encuesta()
        {
            this.resultado = new HashSet<resultado>();
        }
    
        public int iddetalle_encuesta { get; set; }
        public Nullable<int> idencuesta { get; set; }
        public string Nombre { get; set; }
        public string Titulo { get; set; }
        public Nullable<bool> Requerido { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual encuesta encuesta { get; set; }
        public virtual tipo tipo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resultado> resultado { get; set; }
    }
}
